# setup services 

services:
  
  djangoserver:
    container_name: backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    working_dir: /app

    depends_on:
      - db

    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=ITI_graduationProject
      - DB_PORT=5432

  # set up db

  db:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: ITI_graduationProject
  
    ports:
      - "5432:5432"

    volumes:
      - ./db_data:/var/lib/postgresql/data


